version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "andreasremdt"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
