paths:
  uploads: public/uploads
  static: public
collections_config:
  news:
    path: src/content/news
    output: true
    url: /news/[slug]/
    name: News
    icon: posts
    _enable_editors:
      - content
    _inputs:
      title:
        type: text
        label: News Title
      excerpt:
        type: textarea
        label: Excerpt
      image:
        type: image
        label: Thumbnail Image
        options:
          width: 1300
          resize_style: cover
      created_at:
        type: date
        label: Created At

timezone: Europe/Berlin
commit_templates:
  - template_string: "{commit_type}: {message|trim}"
    _inputs:
      commit_type:
        type: select
        options:
          values:
            - feature
            - fix
            - refactor
            - content
